# This is a basic workflow to help you get started with Actions

name: geekdojo-com__pr-verify

# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pr-verify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup DocFX
        run: |
          sudo apt update
          sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          sudo apt-add-repository 'deb https://download.mono-project.com/repo/ubuntu stable-focal main'
          sudo apt install -y mono-complete
          sudo apt install -y mono-runtime mono-devel msbuild
          sudo apt install -y unzip
          curl -L https://github.com/dotnet/docfx/releases/download/v2.58.3/docfx.zip --output docfx.zip
          unzip -n docfx.zip
          
      - name: DocFX Build
        working-directory: ${{ github.workspace }}
        run: mono docfx.exe build docfx.json --warningsAsErrors
        continue-on-error: false
        
      - name: Create status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BUILD_COMMIT=$(git rev-parse HEAD)
          curl \
          -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/geekdojo-ofc/geekdojo-com/check-runs \
          -d '{"name":"build", "head_sha": "'"$BUILD_COMMIT"'", "status": "completed", "conclusion": "success" }'
