# This is a basic workflow to help you get started with Actions

name: geekdojo-com__pr-verify

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
          
      - name: DocFX Build
        working-directory: ${{ github.workspace }}
        run: docfx build docfx.json --warningsAsErrors
        continue-on-error: false
